/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package dataflow.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Summary extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8493859024166826375L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Summary\",\"namespace\":\"dataflow.model\",\"fields\":[{\"name\":\"city\",\"type\":{\"type\":\"string\",\"java-class\":\"java.lang.String\"}},{\"name\":\"activities\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"EventStatistics\",\"fields\":[{\"name\":\"eventSubject\",\"type\":{\"type\":\"record\",\"name\":\"Subject\",\"fields\":[{\"name\":\"type\",\"type\":{\"type\":\"string\",\"java-class\":\"java.lang.String\"}},{\"name\":\"id\",\"type\":\"int\"}]}},{\"name\":\"activities\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Activity\",\"fields\":[{\"name\":\"eventType\",\"type\":{\"type\":\"string\",\"java-class\":\"java.lang.String\"}},{\"name\":\"pastWeekCount\",\"type\":\"long\"},{\"name\":\"pastWeekUniqueCount\",\"type\":\"long\"},{\"name\":\"pastMonthCount\",\"type\":\"long\"},{\"name\":\"pastMonthUniqueCount\",\"type\":\"long\"}]},\"java-class\":\"java.util.ArrayList\"}}]},\"java-class\":\"java.util.ArrayList\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Summary> ENCODER =
      new BinaryMessageEncoder<Summary>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Summary> DECODER =
      new BinaryMessageDecoder<Summary>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Summary> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Summary> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Summary>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Summary to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Summary from a ByteBuffer. */
  public static Summary fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String city;
  @Deprecated public java.util.List<dataflow.model.EventStatistics> activities;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Summary() {}

  /**
   * All-args constructor.
   * @param city The new value for city
   * @param activities The new value for activities
   */
  public Summary(java.lang.String city, java.util.List<dataflow.model.EventStatistics> activities) {
    this.city = city;
    this.activities = activities;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return city;
    case 1: return activities;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: city = (java.lang.String)value$; break;
    case 1: activities = (java.util.List<dataflow.model.EventStatistics>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'city' field.
   * @return The value of the 'city' field.
   */
  public java.lang.String getCity() {
    return city;
  }

  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.String value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'activities' field.
   * @return The value of the 'activities' field.
   */
  public java.util.List<dataflow.model.EventStatistics> getActivities() {
    return activities;
  }

  /**
   * Sets the value of the 'activities' field.
   * @param value the value to set.
   */
  public void setActivities(java.util.List<dataflow.model.EventStatistics> value) {
    this.activities = value;
  }

  /**
   * Creates a new Summary RecordBuilder.
   * @return A new Summary RecordBuilder
   */
  public static dataflow.model.Summary.Builder newBuilder() {
    return new dataflow.model.Summary.Builder();
  }

  /**
   * Creates a new Summary RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Summary RecordBuilder
   */
  public static dataflow.model.Summary.Builder newBuilder(dataflow.model.Summary.Builder other) {
    return new dataflow.model.Summary.Builder(other);
  }

  /**
   * Creates a new Summary RecordBuilder by copying an existing Summary instance.
   * @param other The existing instance to copy.
   * @return A new Summary RecordBuilder
   */
  public static dataflow.model.Summary.Builder newBuilder(dataflow.model.Summary other) {
    return new dataflow.model.Summary.Builder(other);
  }

  /**
   * RecordBuilder for Summary instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Summary>
    implements org.apache.avro.data.RecordBuilder<Summary> {

    private java.lang.String city;
    private java.util.List<dataflow.model.EventStatistics> activities;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(dataflow.model.Summary.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.city)) {
        this.city = data().deepCopy(fields()[0].schema(), other.city);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.activities)) {
        this.activities = data().deepCopy(fields()[1].schema(), other.activities);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Summary instance
     * @param other The existing instance to copy.
     */
    private Builder(dataflow.model.Summary other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.city)) {
        this.city = data().deepCopy(fields()[0].schema(), other.city);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.activities)) {
        this.activities = data().deepCopy(fields()[1].schema(), other.activities);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'city' field.
      * @return The value.
      */
    public java.lang.String getCity() {
      return city;
    }

    /**
      * Sets the value of the 'city' field.
      * @param value The value of 'city'.
      * @return This builder.
      */
    public dataflow.model.Summary.Builder setCity(java.lang.String value) {
      validate(fields()[0], value);
      this.city = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'city' field.
      * @return This builder.
      */
    public dataflow.model.Summary.Builder clearCity() {
      city = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'activities' field.
      * @return The value.
      */
    public java.util.List<dataflow.model.EventStatistics> getActivities() {
      return activities;
    }

    /**
      * Sets the value of the 'activities' field.
      * @param value The value of 'activities'.
      * @return This builder.
      */
    public dataflow.model.Summary.Builder setActivities(java.util.List<dataflow.model.EventStatistics> value) {
      validate(fields()[1], value);
      this.activities = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'activities' field has been set.
      * @return True if the 'activities' field has been set, false otherwise.
      */
    public boolean hasActivities() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'activities' field.
      * @return This builder.
      */
    public dataflow.model.Summary.Builder clearActivities() {
      activities = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Summary build() {
      try {
        Summary record = new Summary();
        record.city = fieldSetFlags()[0] ? this.city : (java.lang.String) defaultValue(fields()[0]);
        record.activities = fieldSetFlags()[1] ? this.activities : (java.util.List<dataflow.model.EventStatistics>) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Summary>
    WRITER$ = (org.apache.avro.io.DatumWriter<Summary>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Summary>
    READER$ = (org.apache.avro.io.DatumReader<Summary>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
